Create Animal Table -Vet Clinic Database
harshi0102/vet-clinic-project pull request #1
Opened 2023-06-12 14:46 UTC by harshi0102

I created a table called animals in the vet clinic database. I also inserted the required data and perform some Query operations as shown in the screenshots below

![image](https://github.com/harshi0102/vet-clinic-project/assets/108334376/e7fd7f99-6308-4422-af7c-3bfe6e106b9f)
![image](https://github.com/harshi0102/vet-clinic-project/assets/108334376/2d2723e3-88f8-4e82-8f6c-5d8340d320f9)

2023-06-12 15:53 UTC, mukhammadrizooff requested changes
Hi @harshi0102, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media0.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Highlights
- Correct GitFlow ✔️ 
- Good implementations ✔️
- Descriptive `README` file ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-12 15:53 UTC, mukhammadrizooff commented on data.sql
> +VALUES(1, 'Agumon', '2020-02-03', 0, true, 10.23),
- [ ] [REQUIRED] Good job so far! Please remove the `id` from your `data` 🙏🏼 

- `[HINT]`

```sql
 INSERT INTO animals (name, date_of_birth, escape_attempts, neutered, weight_kg)
   VALUES ('Agumon', '2020/2/3', '0', 'true', '10.23');
 INSERT INTO animals (name, date_of_birth, escape_attempts, neutered, weight_kg)
   VALUES ('Gabumon', '2018/11/15', '2', 'true', '8.0');
 INSERT INTO animals (name, date_of_birth, escape_attempts, neutered, weight_kg)
   VALUES ('Pikachu', '2021/01/07', '1', 'false', '15.04');
 INSERT INTO animals (name, date_of_birth, escape_attempts, neutered, weight_kg)
   VALUES ('Devimon', '2017/05/12', '5', 'true', '11.0');
```

2023-06-13 06:52 UTC, harshi0102 commented
According to the feedback of removing ID from data.sql, I removed that now from code written in sql.

2023-06-13 07:08 UTC, mikethreels approved these changes
Hi Harishika, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- good job implementing the requested changes.
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-13 07:09 UTC, merged