Query-Multiple tables
harshi0102/vet-clinic-project pull request #3
Opened 2023-06-14 15:22 UTC by harshi0102

2023-06-14 16:02 UTC, bobb-Rob requested changes
## STATUS: CHANGES REQUIRED ♻️
Hi @harshi0102, 

Good job so far! 👏👏👏 
There are some issues that you still need to work on to go to the next project but you are almost there!  😃 
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>
![](https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)

## Highlights
✅ Correct use of Gitflow
✅ Very descriptive Pull Request(PR)
✅ Neat Commit messages

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-14 16:02 UTC, bobb-Rob commented on schema.sql
> +);
### You did well on this project.

- [ ] Based on the project requirement, you have done very well in using the ALTER TABLE keyword to add the `species_id` and `vet_id` columns, but I also noticed that you have manually added the same columns to the animal table like so 👇🏾 

<img width="181" alt="image" src="https://github.com/harshi0102/vet-clinic-project/assets/84156714/108add3d-bebb-404d-8570-24ed6277fbe5">

This will mostly like to column name collision and possibly through an error. Kindly remove those adding on one 8 and 9 because the ALTER TABLE command will add those columns. 

- [ ] Secondly, I noticed that you have manually removed the species column from the animal table instead of using the keyword ALTER TABLE. Kindly add a command like so 👇🏾 to drop the column `species`.

```sql
ALTER TABLE animals DROP column species;
```

2023-06-15 10:43 UTC, harshi0102 commented
According to the feedback, I have implemented the required changes .

2023-06-15 11:02 UTC, AnselemOdims approved these changes
### Hi  @harshi0102 🙋‍♀️, 
Good job in making the required changes 👏 

# STATUS APPROVED ✔
Your project is complete!  There is nothing else to say other than... it's time to merge it 🔗 🚢 
Congratulations! 🎉 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers 🥂  and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Use the tag @AnselemOdims for a quicker reply


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-15 11:08 UTC, merged